name: 'nbconvert-artifacts'
description: 'Export .ipynb files'


branding:
  icon: "archive"
  color: "purple"


inputs:
  environment-file:
    description: 'Path to the conda env file required to run and export notebooks'
    required: true


runs:
  using: "composite"
  steps:

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: "" 
        environment-file: ${{ inputs.environment-file }}
        auto-activate-base: false

    - name: Ensure Convert tools are installed
      shell: bash -l {0} 
      run: |
        if ! command -v jupyter &> /dev/null; then
            echo "Jupyter not found, installing..."
            conda install -y jupyter nbconvert || pip install jupyter nbconvert
        else
            echo "Jupyter is already installed."
        fi

    - name: Run and compile notebooks recursively
      shell: bash -l {0}
      run: |
        shopt -s globstar
        echo "Converting notebooks..."
        jupyter nbconvert --to html --execute **/*.ipynb