name: 'nbconvert'
description: 'Export .ipynb files'
author: 'Vital de Nodrest'


branding:
  icon: "archive"
  color: "purple"


inputs:
  environment-file:
    description: 'Path to the conda env file required to run and export notebooks. It must contain name:notebook-env.'
    required: true


runs:
  using: "composite"
  steps:

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: ${{ inputs.environment-file }}

    - name: Ensure Jupyter tools are installed
      shell: bash -l {0}
      run: |
        conda install -y jupyter nbconvert || pip install jupyter nbconvert

    - name: Run and compile notebooks recursively
      shell: bash -l {0}
      run: |
        shopt -s globstar
        echo "Converting notebooks..."
        jupyter nbconvert --to html --execute **/*.ipynb