name: 'nbconvert'
description: 'Export .ipynb files'
author: 'Vital de Nodrest'


branding:
  icon: "archive"
  color: "purple"


inputs:

  environment-file:
    description: 'Path to the conda env file required to run and export notebooks.'
    required: true
  
  enable-html:
    description: 'Should the notebooks be exported to html?'
    type: boolean
    required: false
    default: true

  enable-pdf:
    description: 'Should the notebooks be exported to pdf?'
    type: boolean
    required: false
    default: false


runs:
  using: "composite"
  steps:

    - name: Install TeX Live if .pdf
      shell: bash -l {0}
      run: |
        if ${{ inputs.enable-pdf }}; then   
          sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-plain-generic
        fi

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: ${{ inputs.environment-file }}

    - name: Ensure Jupyter tools are installed
      shell: bash -l {0}
      run: |
        conda install -y jupyter nbconvert || pip install jupyter nbconvert

    - name: Run and compile notebooks recursively
      shell: bash -l {0}
      run: |
        shopt -s globstar
        if ${{ inputs.enable-html }}; then
          echo "Converting notebooks to html..."
          jupyter nbconvert --to html --execute **/*.ipynb
        fi
        if ${{ inputs.enable-pdf }}; then
          echo "Converting notebooks to pdf..."
          jupyter nbconvert --to pdf --execute **/*.ipynb
        fi
